#pragma once

#include "robin/color/gradient_lookup.h"
#include "robin/color/pixel_accumulation.h"
#include "robin/config.h"

#include <utility>
#include <vector>

class Accumulation {
public:
	explicit Accumulation(Config& config);

	[[nodiscard]] PixelAccumulation& getPixelFrequency(int x, int y);

	[[nodiscard]] int getMaxColorFrequency() const;

	void incrementFrequency(float x, float y, float color);

	void merge(const Accumulation& local_buffer);

	void clear();

private:
	Config& config_;

	// flattened histogram representing the pixels on the screen.
	// as a point (x, y) is generated by the random function, increment
	// the corresponding pixel value in the histogram.
	// the frequency of the pixels determines the image color
	std::vector<PixelAccumulation> histogram_{};

	// a lookup table for sampling continuous gradient RGB tuples, generated
	// from a finite set of gradient stop points
	GradientLookup gradient_lookup_;

	std::pair<int, int> projectToScreen(float x, float y);
};
